# Generated by Django 4.0 on 2022-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
